spring.application.name=productos

spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:37005/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fRJIbOdoGmuGsPhGtBigHaUboFaxwJgj

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Habilita la actualización automática de la estructura de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true


# Muestra el SQL generado en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
